[KnownCompositors]

Hyprland/Name=Hyprland
Hyprland/Comment=tiling window manager for X11

kwin_wayland/Name=kwin_wayland
kwin_wayland/Comment=window manager with the NEXTSTEP look and feel

labwc/Name=labwc
labwc/Comment=Amiga look alike window manager

sway/Name=Sway
sway/Comment=highly configurable X window manager

wayfire/Name=Wayfire
wayfire/Comment=Window manager for X
