[KnownCompositors]

hikari/Name=hikari
hikari/Comment=

Hyprland/Name=Hyprland
Hyprland/Comment=

kwin_wayland/Name=kwin_wayland
kwin_wayland/Comment=

labwc/Name=labwc
labwc/Comment=

qtile/Name=qtile
qtile/Comment=

river/Name=river
river/Comment=

sway/Name=Sway
sway/Comment=

swayfx/Name=swayfx
swayfx/Comment=

wayfire/Name=Wayfire
wayfire/Comment=





